name: "Code quality"

on: [push, pull_request]

jobs:

  flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up Python 🔧
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies 🔧
        run: |
          python -m pip install --upgrade pip
          pip install -e .['lint']
      - name: Test code quality 🔧
        run: |
          flake8

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Black codestyle 🔧
        uses: psf/black@stable
